/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CreateRouteImport } from './routes/create'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PaiementOrderIdRouteImport } from './routes/paiement.$orderId'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedLibraryRouteImport } from './routes/_authenticated/library'
import { Route as AuthenticatedSongSongIdRouteImport } from './routes/_authenticated/song.$songId'
import { Route as AuthenticatedGenerateSongIdRouteImport } from './routes/_authenticated/generate.$songId'
import { Route as ApiPublicWebhooksSunoRouteImport } from './routes/api/public/webhooks/suno'

const CreateRoute = CreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PaiementOrderIdRoute = PaiementOrderIdRouteImport.update({
  id: '/paiement/$orderId',
  path: '/paiement/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLibraryRoute = AuthenticatedLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSongSongIdRoute = AuthenticatedSongSongIdRouteImport.update({
  id: '/song/$songId',
  path: '/song/$songId',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGenerateSongIdRoute =
  AuthenticatedGenerateSongIdRouteImport.update({
    id: '/generate/$songId',
    path: '/generate/$songId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicWebhooksSunoRoute = ApiPublicWebhooksSunoRouteImport.update({
  id: '/api/public/webhooks/suno',
  path: '/api/public/webhooks/suno',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/create': typeof CreateRoute
  '/library': typeof AuthenticatedLibraryRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/paiement/$orderId': typeof PaiementOrderIdRoute
  '/generate/$songId': typeof AuthenticatedGenerateSongIdRoute
  '/song/$songId': typeof AuthenticatedSongSongIdRoute
  '/api/public/webhooks/suno': typeof ApiPublicWebhooksSunoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/create': typeof CreateRoute
  '/library': typeof AuthenticatedLibraryRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/paiement/$orderId': typeof PaiementOrderIdRoute
  '/generate/$songId': typeof AuthenticatedGenerateSongIdRoute
  '/song/$songId': typeof AuthenticatedSongSongIdRoute
  '/api/public/webhooks/suno': typeof ApiPublicWebhooksSunoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/create': typeof CreateRoute
  '/_authenticated/library': typeof AuthenticatedLibraryRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/paiement/$orderId': typeof PaiementOrderIdRoute
  '/_authenticated/generate/$songId': typeof AuthenticatedGenerateSongIdRoute
  '/_authenticated/song/$songId': typeof AuthenticatedSongSongIdRoute
  '/api/public/webhooks/suno': typeof ApiPublicWebhooksSunoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/create'
    | '/library'
    | '/profile'
    | '/paiement/$orderId'
    | '/generate/$songId'
    | '/song/$songId'
    | '/api/public/webhooks/suno'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/create'
    | '/library'
    | '/profile'
    | '/paiement/$orderId'
    | '/generate/$songId'
    | '/song/$songId'
    | '/api/public/webhooks/suno'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/create'
    | '/_authenticated/library'
    | '/_authenticated/profile'
    | '/paiement/$orderId'
    | '/_authenticated/generate/$songId'
    | '/_authenticated/song/$songId'
    | '/api/public/webhooks/suno'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  CreateRoute: typeof CreateRoute
  PaiementOrderIdRoute: typeof PaiementOrderIdRoute
  ApiPublicWebhooksSunoRoute: typeof ApiPublicWebhooksSunoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/create': {
      id: '/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof CreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/paiement/$orderId': {
      id: '/paiement/$orderId'
      path: '/paiement/$orderId'
      fullPath: '/paiement/$orderId'
      preLoaderRoute: typeof PaiementOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/library': {
      id: '/_authenticated/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof AuthenticatedLibraryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/song/$songId': {
      id: '/_authenticated/song/$songId'
      path: '/song/$songId'
      fullPath: '/song/$songId'
      preLoaderRoute: typeof AuthenticatedSongSongIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/generate/$songId': {
      id: '/_authenticated/generate/$songId'
      path: '/generate/$songId'
      fullPath: '/generate/$songId'
      preLoaderRoute: typeof AuthenticatedGenerateSongIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/webhooks/suno': {
      id: '/api/public/webhooks/suno'
      path: '/api/public/webhooks/suno'
      fullPath: '/api/public/webhooks/suno'
      preLoaderRoute: typeof ApiPublicWebhooksSunoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedLibraryRoute: typeof AuthenticatedLibraryRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedGenerateSongIdRoute: typeof AuthenticatedGenerateSongIdRoute
  AuthenticatedSongSongIdRoute: typeof AuthenticatedSongSongIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedLibraryRoute: AuthenticatedLibraryRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedGenerateSongIdRoute: AuthenticatedGenerateSongIdRoute,
  AuthenticatedSongSongIdRoute: AuthenticatedSongSongIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  CreateRoute: CreateRoute,
  PaiementOrderIdRoute: PaiementOrderIdRoute,
  ApiPublicWebhooksSunoRoute: ApiPublicWebhooksSunoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
